[build-system]
requires = ["hatchling>=1.32.0,<2"]
build-backend = "hatchling.build"


[tool.hatch.build]
include = [
  "src/clonepulse/**",
  "README.md",
  "CHANGELOG.md",
  "LICENSE",
  "clonepulse/**",
]

[tool.hatch.build.targets.wheel]
packages = ["src/clonepulse"]
sources = ["src"]

[tool.hatch.version]
path = "src/clonepulse/__about__.py"

[project]
name = "clonepulse"
dynamic = [
  "version",
]
authors = [
  { name="Per Jensen", email="clonepulse@pm.me" },
]
description = """Your GitHub clone stats, visualized and celebrated."""
readme = { file = "README.md", content-type = "text/markdown" }
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: POSIX :: Linux",
]


dependencies = [
    "requests>=2.34.2,<3",
    "pandas>=3.0.5,<4",
    "matplotlib>=3.11.1,<4",
]

[project.optional-dependencies]
dev = [
  "pytest>=9.1.1,<10",
  "wheel>=0.48.0,<1",
  "coverage>=7.16.0,<8",
  "pytest-cov>=7.1.0,<8",
]

packaging = [
  "build>=1.6.0,<2",
  "hatchling>=1.32.0,<2",
  "hatch>=1.18.0,<2",
  "twine>=7.0.0,<8",
]

[project.urls]
Homepage = "https://github.com/per2jensen/clonepulse"
Issues =   "https://github.com/per2jensen/clonepulse/issues"
