name: Pytest
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  python3-unit-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Install required system packages
        run: |
          sudo apt update
          sudo apt install -y git python3 python3-venv python3-pip

      - name: Create and prepare Python virtual environment
        run: |
          if [[ -d venv* ]]; then
            rm -rf venv*
          fi
          ./build.sh

      - name: Run pytest
        run: |
          . venv*/bin/activate  # activate the newly created venv (venv or venv-YYYYMMDD-N)
          coverage erase
          pytest tests/

